---
title: "EDA_Thieman"
format: html
editor: visual
---

```{r, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(lme4)
df <- read.csv("clean_data.csv")

df <- df %>%
  mutate(Time = num_squish/freq)
```

```{r}
head(df)
df <- df%>% filter(Cycle != "A")
```

```{r}
ggplot(df, aes(y = Estatic_rel, x = Porosity)) + 
  geom_boxplot()

```

```{r}
 ggplot(df, aes(y = Estatic_rel, x = ChemIndex)) + 
  geom_boxplot()
```
```{r}

ggplot(df, aes(
    x = Time,
    y = Estatic_rel,
    group = interaction(ChemIndex, Porosity),
    color = interaction(ChemIndex, Porosity)
  )) +
geom_point(size = 2) +
  labs(
    title = "Estatic_rel Across Time by Foam Type and Porosity",
    x = "Num_Squish",
    y = "Standardized Estatic Stange",
    color = "chemindex / Porosity"
  ) +
  theme_minimal()

```
```{r}
ggplot(df, aes(x = ChemIndex, y = Estatic_rel, fill = Porosity)) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  labs(title = "Estatic_rel by ChemIndex and Porosity",
       x = "ChemIndex",
       y = "Estatic_rel") +
  theme_minimal()
```

```{r}
ggplot(df, aes(
    x = Time,
    y = Estatic_rel,
    group = interaction(ChemIndex, Porosity),
    color = interaction(ChemIndex, Porosity)
  )) +
geom_point(size = 2) +
  labs(
    title = "Estatic_rel Across Time by Foam Type and Porosity",
    x = "Time",
    y = "Standardized Estatic Stange",
    color = "chemindex / Porosity"
  ) +
  theme_minimal()
```

$$
\widehat{\text{Estatic_relative}} = stress + Log(time):Porosity*ChemIndex + + freq +  num_squish +  \epsilon\\

a_i = \alpha _0 + \alpha_1 Stress_kPa + log(Time):Porosity*ChemIndex + freq +  num_squish + u_i \\
b_i = \beta _0 + \beta_1 (Stress) + \beta_2 (Frequency) + \beta_3 (Number Squish) + \beta_I (Porosity * ChemIndex) + \beta_5 (amp*ChemIndex) + \beta_6 ( freq * num_squish) + v_i \\

Y_{ij} = (\alpha _0 + \alpha_1 (Stress) + \alpha_2 (Frequency) + \alpha_3 (Number Squish) + \alpha_4 I (Porosity * ChemIndex) + \alpha_5 (amp*ChemIndex) + \alpha_6 ( freq * num_squish) + u_i) + (\beta _0 + \beta_1 (Stress) + \beta_2 (Frequency) + \beta_3 (Number Squish) + \beta_I (Porosity * ChemIndex) + \beta_5 (amp*ChemIndex) + \beta_6 ( freq * num_squish) + v_i)(Time) + \epsilon_i


$$
```{r}

First_model <- lmer(Estatic_rel ~  log(Time):Porosity*ChemIndex + freq +  num_squish+  (1|SampleCode), data = df)

summary(First_model)

library(nlme)
m1 <- lme(Estatic_rel ~  log(Time):Porosity*ChemIndex +  freq + num_squish ,random=~1|SampleCode,data=df)
anova(m1)


```
```{r}
library(ggeffects)

# Get predicted values for num_squish across Porosity and ChemIndex
preds <- ggpredict(First_model, terms = c("num_squish", "Porosity", "ChemIndex"))
ggplot(preds, aes(x = x, y = predicted)) +
  geom_line(color = "steelblue", size = 1) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), fill = "steelblue", alpha = 0.2) +
  facet_wrap(~interaction(group, facet), ncol = 2) +  # 2 columns, change as needed
  labs(
    x = "Number of Squish",
    y = "Predicted Estatic_rel",
    title = "Predicted Estatic_rel by num_squish across Porosity x ChemIndex",
    subtitle = "Each panel is a Porosity × ChemIndex combination"
  ) +
  theme_minimal(base_size = 14)

```
```{r}
ggplot(df, aes(y = Estatic_rel, x = num_squish, group))+
  geom_point(aes(x = num_squish, group = interaction(ChemIndex, Porosity)), color = interaction(ChemIndex, Porosity))
```

$$
b_i = \beta _0 + \beta_1 (Stress) + \beta_2 (Frequency)  + \beta_3 (Porosity * ChemIndex) + \beta_4 (amp*ChemIndex) + \beta_5 ( freq * numSquish) + v_i
$$

```{r}
library(emmeans)

emmean <- emmeans(First_model,~ Porosity *  ChemIndex)

p <- ggplot(df, aes(y =  Porosity * ChemIndex , x = emmean)) +
  geom_point(size = 3, color = "black") +
  geom_errorbarh(aes(xmin = lower.CL, xmax = upper.CL), height = 0.2, color = "blue", alpha = 0.5) +
  facet_wrap(~ First_model, nrow = 1) + 
  xlab("Estimated Marginal Mean") +
  ylab("ChemIndex * Porosity") +
  theme_minimal()
```
```{r}
plot(emmean)
```

